name: batch CI/CD Pipeline

on:
  push:
    branches:
      - '**'  # This will run on push to any branch
  pull_request:
    branches:
      - 'main'  # This will run only on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_batch.txt
        pip install pytest

    - name: Run tests
      run: pytest tests/test_batch.py

    - name: Build Docker image
      run: docker build -t yotam433/mid_project_batch:latest -f docker/Dockerfile.batch .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push image to Docker Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: docker push yotam433/mid_project_batch:latest
